### ISSUE TITLE
Selecting "Load" crashes app

### ISSUE THREAD

**Issue by amis92** [BlueWinds/bluescribe#1]
When selecting Load on default entry (A song of ice and fire) the website stops working (loader ring forever).

**Comment by BlueWinds** [comment]
I hope to have this (and a bunch of other issues) fixed sometime tomorrow; I pushed up a release that wasn't sufficiently tested, and am currently writing a bunch of automated tests to ensure it doesn't happen again.

**Comment by BlueWinds** [comment]
I've deployed a version that will at least dump you back at the main page if you load a game system with errors, rather than leaving you in limbo.

Still need to look into ASoIF and see what's up with it. It's the default entry because it's first alphabetically, not for any fancier reason.
