### ISSUE TITLE
Implement second-pass on `modifiers` to work with modifiers that trigger off total roster points

### ISSUE THREAD

**Issue by BlueWinds** [BlueWinds/bluescribe#10]
I have here a slightly modified version of the HH data files that a data editor was working on, which demonstrate the problem nicely:

[HH_V2_Horus_Heresy_2022_-_Copy.zip](https://github.com/BlueWinds/bluescribe/files/11827006/HH_V2_Horus_Heresy_2022_-_Copy.zip)

- Click Create NewRoster.rosz
    Faction: LA - XIV: Death Guard
        Detachment: Crusade
- Add HQ -> Praetor, Cataphractii
- Praetor, Cataphractii -> Select Command Squad, Cataphractii (55 Pts)

This should have a `Value` which matches the points cost, but it does not.

Basically what's happening is that the the `selectionEntry` is being calculated in `getEntry` when a new entry is added. At the time, the total roster `pts` is 0: there are no entries in the roster, so the modifier to set the selection's `Value` repeats 0 times. Refreshing the roster doesn't help; the same thing happens again, where the roster doesn't have a total points value until after the selectionEntry's modifiers have already been parsed.

BlueScribe needs to switch to a two-pass system, where it recalculates any relevant modifiers once the roster is finished updating, and then re-updates the roster as needed.

**Comment by Sticksman** [comment]
Where does this problem actually manifest? It looks as though the points costs get updated properly at the top of the page
![Screenshot 2023-06-21 at 9 25 59 PM](https://github.com/BlueWinds/bluescribe/assets/2308901/fa95505c-2aee-4e33-a90b-9dcf80a9b925)

**Comment by BlueWinds** [comment]
The points get updated, but the `Value` doesn't - Value being a second costType in the datafiles. Compare the above to Battlescribe:

![image](https://github.com/BlueWinds/bluescribe/assets/3003404/1471c25e-2811-4d1a-98c4-ba7000d7e2ac)

Master Of the Legion has a `<modifier>` adding +1 `value`, with `<repeat>` equal  to the number of points in the roster.

**Comment by Sticksman** [comment]
I see. Let me see what I can do.

**Comment by Sticksman** [comment]
Ok, so I think I've sort of wrapped my head around some of this. I guess my only question is: what is the "Value" supposed to represent? Is it supposed to be value == points? Or is it value == points + modifiers? Or something else entirely?
