### ISSUE TITLE
Page not opening.

### ISSUE THREAD

**Issue by ff5271** [BlueWinds/bluescribe#13]
When I launch the page https://bluewinds.github.io/bluescribe/ it opens into a spinning page but nothing happens.

**Comment by DanieleSuppo** [comment]
I guess you will be asked to provide at least the browser used and to check if there is any error on the console.
Here is a list of ways to open the console for almost all browsers and SO:
https://appuals.com/open-browser-console/
A screenshot of the error would be helpful.

**Comment by ff5271** [comment]
Okay. It was firefox. I will try again on a different browser.

**Comment by BlueWinds** [comment]
Mostly what I need is the console logs; you can open the console with `F12`, or `ctrl-shift-i` - the page being blank doesn't really tell me what's gone wrong in a way I can help with! :)

**Comment by chrismason01** [comment]
think i have the same issue - chrome on mac - spinning blue wheel - no drop down options

screenshot of console attached

<img width="878" alt="Screenshot 2023-06-27 at 16 27 30" src="https://github.com/BlueWinds/bluescribe/assets/55393512/04b03437-d70b-4f15-9875-6187ba0326e6">

**Comment by chrismason01** [comment]
tried on safari as well and no dice
