### ISSUE TITLE
Xenos Rampant Shared Selection Entry Groups default value incorrect

### ISSUE THREAD

**Issue by DaeronAlagos** [BlueWinds/bluescribe#17]
BlueScribe Version: 0.5.0
Game System: Xenos Rampant

Steps to reproduce:
1. Load Xenos Rampant game system
2. Create new Roster
3. Add a Standard Detachment (24pts limit)
4. Add `Light Infantry` unit
5. SSEGs have defaulted to the highest value

Expected behaviour:
SSEGs should have `None` selected by default.

Additional notes:
To be able to set all SSEGs to `None`, it has to be done in a specific order (Species then Class then ForceField). If done in a different order it is impossible to set the remaining item to `None`.

**Comment by Sticksman** [comment]
@DaeronAlagos two questions:
1. What is SSEG?
2. Can you screenshot it? I'm not seeing any selection defaults when selecting light infantry

**Comment by BlueWinds** [comment]
I released a buggy version the other day which had a major regression around default selections; I fixed it a few hours later, but looks like @DaeronAlagos had the misfortune to run into it during that window. Sorry about that!

I  believe the general fix I applied resolves this; if you're still seeing something weird, please let me know and I can look into it further.
