### ISSUE TITLE
Dystopian Wars 3.19.03 : Cannot read properties of undefined (Reading 'map')

### ISSUE THREAD

**Issue by Void-kraken** [BlueWinds/bluescribe#21]
Browser: Chrome, Version 114.0.5735.143 (Official Build) (64-bit)
Device : Chromebook (Coral), occurs also on Android 13 / Pixel 7 Pro

Notes:
- Occurs regardless of faction chosen in step 3, battlefleet chosen in step 4, or unit chosen in step 5
- Dataset works normally in Battlescribe so is not believed to be an error in data setup

Steps to reproduce
1. Load Dystopian Wars 3.19.03 data
2. Create a new Roster (no specifics made any difference here)
3. Select the Enlightened faction
4. Select an Englightened Frontline Battlefleet
5. Click to add a Flagship, select Hypatia Generator Ship

Error thrown to console
`
TypeError: Cannot read properties of undefined (reading 'map')
    at utils.js:87:47
    at Array.map (<anonymous>)
    at hf (utils.js:82:8)
    at Selection.js:346:34
    at Array.map (<anonymous>)
    at cd (Selection.js:330:34)
    at Co (react-dom.production.min.js:167:137)
    at Cu (react-dom.production.min.js:290:337)
    at wc (react-dom.production.min.js:280:389)
    at yc (react-dom.production.min.js:280:320)
`

**Comment by BlueWinds** [comment]
Thanks for the report and the detailed repro steps! Fixed in BlueScribe 0.5.5, released a few minutes ago.

The flagship had a <profile> entry with no <characteristic>s attached, which I didn't know was possible.
