### ISSUE TITLE
[40K 10th Ed] - League of Votann / Hearthkyn Warrior : Error on Model Count

### ISSUE THREAD

**Issue by RadiatedCoordination** [BlueWinds/bluescribe#23]
Platform : Desktop Computer
OS : Windows 10
Browser : Firefox v113.0.1

Steps to reproduce :
1. On [the web app](https://bluewinds.github.io/bluescribe/) : load Warhammer 40k 10th edition
2. Create a new roster
3. Add a _Xenos - League of Votann_ force
4. Attempt to add a Unit of Hearthkyn Warriors

Status : 
- Many Nan Errors (probably many iterations of the same error)
![image](https://github.com/BlueWinds/bluescribe/assets/140544819/6c9cead5-968d-4e3e-bbaa-2d444d9a1d7c)
![image](https://github.com/BlueWinds/bluescribe/assets/140544819/670a4fac-ff72-435d-9153-4b4a995b296f)
- Interactions with the size of the squad is glitchy (Number of warriors blink on and off depending on interaction with number inputs)
![image](https://github.com/BlueWinds/bluescribe/assets/140544819/1de203d0-7797-4b3b-a2d1-740c4bf96510)

[Roster.zip](https://github.com/BlueWinds/bluescribe/files/12164233/Roster.zip)

**Comment by RadiatedCoordination** [comment]
Same result on Edge (v115.0.1901.183)
![image](https://github.com/BlueWinds/bluescribe/assets/140544819/921f6248-7d22-42d9-a5ca-2bfe2cc09d25)

**Comment by BlueWinds** [comment]
Thanks for the report! Fixed in 0.6.2. Was a pretty obscure cause that's hard to describe, related to how entries are processed in bluescribe when they're not present in the roster.
