### ISSUE TITLE
Unable to Save Dystopian Wars rosters (using v0.6.2 of Bluescribe)

### ISSUE THREAD

**Issue by Void-kraken** [BlueWinds/bluescribe#24]
Reproduced using Chrome Os on Chromebook Coral, Bluescribe v0.6.2

BTW, I'm not involved with the Dystopian Wars data development, just an interested user!

Steps to Reproduce
1. Download/update Dystopian Wars to v3.19.03 (latest version)
2. Create a new Roster
3. Add an Englightened faction, Enlightened Frontline Battlefleet
4. Clickng save beore you add any units works normally - the issue occurs after you add units to it
5. Add any one unit (in my example, I added a Flagship -> Nansen Explorer)
6. Click save

Observed : nothing happens from the UI perspective
The console throws this error
`index.js:44 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at index.js:44:77
    at Array.forEach (<anonymous>)
    at e (index.js:42:28)
    at index.js:47:11
    at Array.forEach (<anonymous>)
    at e (index.js:42:28)
    at index.js:47:11
    at Array.forEach (<anonymous>)
    at e (index.js:42:28)
    at index.js:47:11`

**Comment by BlueWinds** [comment]
Looks like this is a bug related to the fact that DW uses ProfileTypes with no CharacteristicTypes. Fixed in 0.7.1.
