### ISSUE TITLE
How do you actually *add* a unit to a 40k - 10th edition roster?

### ISSUE THREAD

**Issue by rmzg** [BlueWinds/bluescribe#26]
I create a new roster, select aeldari, click on the 'Autarch' link under the 'character' tab, and... then what? I've tried literally every button on the page and nothing takes me back to the page with the tabs of units to add, except the "X" button, which... removes the unit I just tried to add.

![image](https://github.com/BlueWinds/bluescribe/assets/1282791/8520e294-4b9a-40f4-abfb-7bd121f6b3d5)
![image](https://github.com/BlueWinds/bluescribe/assets/1282791/e9586c4f-5dba-45d5-9a4a-24d9980184ca)

**Comment by BlueWinds** [comment]
The "Add Unit" button?

![Untitled](https://github.com/BlueWinds/bluescribe/assets/3003404/1f967dd0-562e-4f2e-9f2d-3c44be3cbc05)

**Comment by BlueWinds** [comment]
The autarch is in the list; it's been added. You were taken to the screen to customize its selections. Add Unit will take you back to the add unit page to start adding more.

**Comment by rmzg** [comment]
THAT'S A BUTTON?!

**Comment by rmzg** [comment]
I thought it was the title for that tab.

**Comment by rmzg** [comment]
This is why we have browser defaults for interactive controls!!!!

**Comment by rmzg** [comment]
Also when I click it why is the autarch under a header that says "New Category (link)" ?

**Comment by BlueWinds** [comment]
Fixed the `New Category (link)` bit - this is a quirk of the 10e data compared to the 9th. Also adjusted the styles on the "add unit" button a touch.
